<?php if(!defined('EFFICIENT_ROOT')) exit();

    // --- Database structure
    
    return array (
      
      'tables'      =>  array (
        'item_src'  =>  'item_db',
        'mob_src'   =>  'mob_db',
        'spawns'    =>  'spawns',
      ),
      
      'item_src'     =>  array (
        'id'        =>  'id',
        'name1'     =>  'name_japanese',
        'name2'     =>  'name_english',
        'type'      =>  'type',
        'value_b'   =>  'price_buy',
        'value_s'   =>  'price_sell',
        'weight'    =>  'weight',
        'attack'    =>  'attack',
        'defence'   =>  'defence',
        'weap_lvl'  =>  'weapon_level',
        'range1'    =>  'range',
        'slots'     =>  'slots',
        'e_jobs'    =>  'equip_jobs',
        'e_upper'   =>  'equip_upper',
        'e_gender'  =>  'equip_genders',
        'e_loc'     =>  'equip_locations',
        'e_lvl'     =>  'equip_level',
        's_refine'  =>  'refineable',
        'view_id'   =>  'view',
        'act'       =>  'script',
        'e_act'     =>  'equip_script',
        'ue_act'    =>  'unequip_script',
        'desc'      =>  'Description',
        'irodesc'   =>  'Description_IRO',
        'droppers'  =>  'Droppers',
        'episode'   =>  'Episode_Info',
      ),
      
      'mob_src'      =>  array (
        'id'        =>  'ID',
        'spr_view'  =>  'Sprite',
        'name1'     =>  'kName',
        'name2'     =>  'iName',
        'mob_lvl'   =>  'LV',
        'mob_HP'    =>  'HP',
        'mob_SP'    =>  'SP',
        'exp'       =>  'EXP',
        'jexp'      =>  'JEXP',
        'mexp'      =>  'MEXP',
        'expper'    =>  'ExpPer',
        'range1'    =>  'Range1',
        'range2'    =>  'Range2',
        'range3'    =>  'Range3',
        'attack1'   =>  'ATK1',
        'attack2'   =>  'ATK2',
        'defence'   =>  'DEF',
        'm_defence' =>  'MDEF',
        'str'       =>  'STR',
        'agi'       =>  'AGI',
        'vit'       =>  'VIT',
        'int'       =>  'INT',
        'dex'       =>  'DEX',
        'luk'       =>  'LUK',
        'size'      =>  'Scale',
        'race'      =>  'Race',
        'element'   =>  'Element',
        'mode'      =>  'Mode',
        'speed'     =>  'Speed',
        'adelay'    =>  'aDelay',
        'amotion'   =>  'aMotion',
        'dmotion'   =>  'dMotion',
        'm_item1'   =>  'MVP1id',
        'm_item2'   =>  'MVP2id',
        'm_item3'   =>  'MVP3id',
        'item1'     =>  'Drop1id',
        'item2'     =>  'Drop2id',
        'item3'     =>  'Drop3id',
        'item4'     =>  'Drop4id',
        'item5'     =>  'Drop5id',
        'item6'     =>  'Drop6id',
        'item7'     =>  'Drop7id',
        'item8'     =>  'Drop8id',
        'item9'     =>  'Drop9id',
        'm_item1p'  =>  'MVP1per',
        'm_item2p'  =>  'MVP2per',
        'm_item2p'  =>  'MVP3per',
        'item1p'    =>  'Drop1per',
        'item2p'    =>  'Drop2per',
        'item3p'    =>  'Drop3per',
        'item4p'    =>  'Drop4per',
        'item5p'    =>  'Drop5per',
        'item6p'    =>  'Drop6per',
        'item7p'    =>  'Drop7per',
        'item8p'    =>  'Drop8per',
        'item9p'    =>  'Drop9per',
        'drops'     =>  'ItemDrops',
        'mdrops'    =>  'BossDrops',
        'spawns'    =>  'Spawns',
        'skills'    =>  'Skills',
      ),
    
      'spawns'      =>  array (
        'map'       =>  'map',
        'title'     =>  'map_name',
        'cx1'       =>  'x1',
        'cx2'       =>  'x2',
        'cy1'       =>  'y1',
        'cy2'       =>  'y2',
        'name1'     =>  'mob_name',
        'mid'       =>  'mob_id',
        'amount'    =>  'amount',
        'delay1'    =>  'delay1',
        'delay1'    =>  'delay2',
        'event'     =>  'event',
      ),
    
    );
